[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "Agent World Extensions"
title = "Agent WorldStreamer (RTMP)"
description = "RTMP streaming extension: captures Isaac Sim viewport and pushes RTMP. Minimal control API (start/stop/status)."
authors = ["agenTW∞rld Team"]
keywords = ["isaac", "streaming", "rtmp", "live", "broadcast", "api", "worldstreamer", "control", "rtmp"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
writeTarget.kit = true
writeTarget.platform = true

[dependencies]
"agent.world.core" = {}
# External streaming stack still relies on GStreamer/NVENC outside Kit

[fswatcher.patterns]
include = ["*.py", "*.toml"]
exclude = ["__pycache__"]

[[python.module]]
name = "omni.agent.worldstreamer.rtmp"

[settings]
# Note: Configuration values come from agentworld-extensions/agent-world-config.json
# These settings provide Isaac Sim carb integration only
"/exts/omni.agent.worldstreamer.rtmp/config_source" = { type="string", default="unified", description="Configuration source: unified agentworld-extensions JSON (RTMP)" }
